//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTGR.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nodes
    {
        public int idx { get; set; }
        public string id { get; set; }
        public string name { get; set; }
        public string parentid { get; set; }
    }
}
